name: Build Pokémon Red ROM

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-rom:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias del sistema
        run: sudo apt-get install -y build-essential make gcc git libpng-dev

      - name: Clonar e instalar RGBDS
        run: |
          git clone https://github.com/gbdev/rgbds.git
          cd rgbds
          make
          sudo make install

      - name: Compilar el proyecto
        run: make

      - name: Subir ROM compilada como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: PokemonRed.gbc
          path: pokered.gbc
